[server]

port = 1897

[browser]

serverAddress = 'localhost'

[theme]

# Primary accent for interactive elements
primaryColor = '#83cf83'

# Background color for the main content area
backgroundColor = '#2b2b2b'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#393939'

# Color used for almost all text
textColor = '#d4d4d4'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: 'sans serif'
font = 'sans serif'
